## Spring boot server config ##
server:
 contextPath: /license-plate-recognition/1.0
 port: 9000
 
config-api:
 url: http://composite-dq01.cars.com/config-api/1.0/rest/config


spring.http.multipart.max-request-size: 10MB